### PR TITLE
allow for prefill prop

### PR DESCRIPTION
**Pull request by SkoebaSteve**
I would like to add the prefill prop from the hosted fields library: https://braintree.github.io/braintree-web/3.26.0/module-braintree-web_hosted-fields.html

### CODE REVIEW

**Comment by nathanstitt** [comment]
Thanks @SkoebaSteve, the code looks great.  If you could be so kind, can you document `prefill` on the `README.md` in the fields section?   If you're unable to do so let me know and I can do it later today.

I can release a new version once that's done.

**Comment by nathanstitt** [comment]
wow!  I think you pushed that up while I was commenting 😁

**Comment by SkoebaSteve** [comment]
@nathanstitt Yeah I just realized it, I need to fix an error regarding the demo, `cannot read property 'numberField' of undefined` so let me just fix it and push it and it should be good.

Thanks for the library, it's been a lifesaver!

**Comment by SkoebaSteve** [comment]
@nathanstitt fixed, ready to go :)

**Comment by nathanstitt** [comment]
Thanks @SkoebaSteve, and great catch on the `onAuthorizationSuccess`. I think that was probably introduced previously.

**Comment by nathanstitt** [comment]
@SkoebaSteve I released this as version `1.1.0` give it a try when you're able.  

I also bumped the dev dependencies which pulled in an updated rollup which required updating the config for the build.  I think it's all ok, but there may be something I missed. 

If you spot anything before I do please let me know.

**Comment by SkoebaSteve** [comment]
Ok just tested it and it works fine! Thanks for releasing it this quick, now I can actually finish my end to end test

**Pull request merged**
